development:
  adapter: mysql2
  encoding: utf8
  database: rdase_dev
  username: rdase 
  password: uberjew 
  host: localhost 
  #socket: /var/run/mysqld/mysqld.sock 

production:
  adapter: mysql2
  encoding: utf8
  database: rddb_prod
  username: rddb 
  password: uberjew 
  # socket: /tmp/mysql.sock
  socket: /var/run/mysqld/mysqld.sock 
